# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 860b2c425d743bf009f4a3808167cb39e802be2a16f48c310a29ba635179c36b303e76d38151d536412cf01443bf14e05bf61b33bd1fa5e2533efbfe0c41531d

test:
  secret_key_base: b79cd36b06b9f7dd38f39f4ec9df3d8e320156607b045814f888d5de136e7b635a9f540c7abfa24913dae8433a726205bb2e69ab84bc07d7d774472808546e39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
